### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Felix14-v2** [hschwar/AccurateBlockPlacement#2]
Hello, you've asked for the source code of the original mod. By a happy coincidence, I didn't delete the repository when I finished translating the mod, so you can find it here:
https://github.com/Felix14-v2/AccurateBlockPlacement

UPD: found another fork with more recend changes:
https://github.com/BurrConnie/AccurateBlockPlacement

**Comment by hschwar** [comment]
Thanks for taking the time to comment here!
The BurrConnie fork is completely up to date and is exactly what I needed.
